### ISSUE TITLE
glyph data server

### ISSUE THREAD

**Issue by yapcheahshen** [g0v/chikage#1]
input : array of unicode character.
output: all data (buhin and frame ) needed for kage to render each char.

example:

input : ["萌","盟"]
output:
{"840C":"99:0:0:0:2:200:175:u8279-03\n99:0:0:0:47:200:195:u660e", //萌
"76DF":"99:0:0:0:6:198:192:u660e-03\n99:0:0:0:-24:200:208:u76bf-04",//盟
"713D":"99:0:0:0:3:200:115:u660e\n99:0:0:0:-20:200:200:u706b-04",//焽
"u660e:"99:0:0:-2: -1:234:177:u65e5-01\n99:0:0:-3:0:197:200:u6708-02",//明
"u660e-03":"99:0:0:1:-2:237:120:u65e5-01\n7:12:7:115:20:115:61:115:103:84:122\n1:2:2:115:20:172:20\n1:22:4:172:20:172:118\n1:2:2:114:49:172:49\n1:2:2:114:78:172:78" 
//and so on....
}

**Comment by caasi** [comment]
Try to output descendants in one array without searching for every possible ancestors.

example input: `http://chikage.linode.caasih.net/exploded/?inputs=%E7%B6%A0%E9%87%8E%E5%B1%B1%E8%8E%8A%E5%A4%AA%E9%99%BD%E5%88%A5%E5%A2%85`

example output:

```
{
  "u7da0": "99:0:0:2:0:155:200:u7cf8-01$99:0:0:75:0:195:200:u5f54",
  "u7cf8-01": "2:0:7:66:16:52:37:35:56$2:7:8:14:45:38:56:48:76$2:0:7:95:39:67:76:34:110$2:0:7:16:113:58:109:95:101$2:7:8:74:78:93:91:101:114$1:32:0:62:109:62:186$2:0:7:38:127:34:155:14:180$2:7:8:75:122:93:136:100:161",
  "u5f54": "1:0:13:67:15:52:67$1:0:2:56:38:139:38$1:22:32:139:38:123:93$1:2:2:52:67:126:67$1:0:0:12:93:188:93$1:32:4:102:93:102:183$2:7:8:30:105:54:118:67:132$2:0:7:22:169:60:153:90:142$2:0:7:183:108:159:120:127:132$2:7:0:110:93:120:142:179:171",
  "u91ce": "99:0:0:-2:0:205:200:u91cc-01$99:0:0:15:0:198:200:u4e88-02",
  "u4e88-02": "1:0:2:97:28:168:28$2:22:7:168:28:158:40:138:59$1:0:2:90:82:178:82$2:22:7:178:82:169:98:153:119$1:32:4:138:82:138:183$2:7:8:111:46:134:56:146:74",
  "u5c71": "1:0:32:100:18:100:165$1:0:13:34:58:34:165$1:2:2:34:165:166:165$1:0:23:166:58:166:165",
  "u838a": "99:0:0:0:2:200:187:u8279-03$99:0:0:0:60:200:195:u58ef",
  "u8279-03": "1:0:0:13:39:187:39$1:0:0:72:13:72:64$1:0:0:128:13:128:64",
  "u58ef": "99:0:0:-6:0:208:200:u723f-01$99:0:0:72:-4:197:205:u58eb",
  "u592a": "1:0:0:17:70:183:70$7:0:7:97:16:97:49:97:142:14:185$2:7:0:102:70:116:142:177:177$2:7:8:74:134:97:149:108:168",
  "u967d": "99:0:0:0:0:190:200:u961d-01$99:0:0:3:0:200:200:u661c-02",
  "u961d-01": "1:2:2:29:28:72:28$2:22:7:72:28:65:49:47:76$2:7:4:47:75:73:100:65:135$1:12:0:29:28:29:186",
  "u661c-02": "99:0:0:64:13:194:85:u65e5$1:0:0:70:96:187:96$2:32:7:112:96:97:127:68:141$1:2:2:100:118:172:118$2:22:4:172:118:171:152:161:179$2:32:7:125:118:105:155:65:177$2:32:7:151:118:137:161:98:186",
  "u65e5": "1:12:13:46:32:46:168$1:2:2:46:32:154:32$1:22:23:154:32:154:168$1:2:2:46:98:154:98$1:2:2:46:168:154:168",
  "u5225": "99:0:0:0:-1:200:199:u20ba0-k01$99:0:0:30:0:201:200:u5202-02",
  "u5202-02": "1:0:0:120:30:120:152$1:0:4:167:15:167:182",
  "u5885": "99:0:0:0:6:200:144:u91ce$99:0:0:0:28:200:200:u571f-04",
  "u571f-04": "99:0:0:0:111:200:186:u571f",
  "u571f": "1:0:0:27:81:173:81$1:0:32:100:17:100:169$1:0:0:14:169:186:169"
}
```

**Comment by yapcheahshen** [comment]
有些extension C的字，轉成urlencode 有問題，造成server error.
可否多接受一個輸入各式：(檢查inputs[0]==="[")
inputs=[ucs32_number,ucs32_number];
這樣你就不必拆字串

從ucs32 陣列轉成字串的方法：
inputs.forEach(function(uni){ return ucs2string(uni) }).join("");

var ucs2string = function (unicode) { 
    if (unicode >= 0x10000 && unicode <= 0x10FFFF) {
      var hi = Math.floor((unicode - 0x10000) / 0x400) + 0xD800;
      var lo = ((unicode - 0x10000) % 0x400) + 0xDC00;
      return String.fromCharCode(hi) + String.fromCharCode(lo);
    } else {
      return String.fromCharCode(unicode);
    }
};

**Comment by yapcheahshen** [comment]
this is ok
http://chikage.linode.caasih.net/exploded/?inputs=%F0%AA%A2%87%F0%AA%A4%A2%F0%AA%AD%B7%F0%AA%B1%B3%F0%AA%B2%89

but this 會噴 500 Internal server error
http://chikage.linode.caasih.net/exploded/?inputs=%F0%AA%A2%87%F0%AA%A4%A2%F0%AA%AD%B7%F0%AA%B1%B3%F0%AA%B2%89%F0%AA%B2%96

**Comment by caasi** [comment]
現在用到的是 `punycode` 裡的 `ucs2.decode` ，我再檢查檢查他哪裡出了問題。

**Comment by caasi** [comment]
resolved in 63f381a

**Comment by yapcheahshen** [comment]
cdn.rawgit.com/g0v/z0y/master/

輸入「日月」，勾「深拆」
server 返回錯誤的json，後面被截掉了。

{"u2a8a3":"99:0:0:2:0:167:200:u559c-01$99:0:0:25:0:252:200:u660e-08","u559c-01":"1:0:0:15:38:100:38$1:0:32:57:15:57:60$1:0:0:20:60:95:60$1:12:13:32:76:32:101$1:2:2:32:76:82:76$1:22:23:82:76:82:101$1:2:2:32:101:82:101$2:7:8:37:105:44:110:49:124$2:0:7:73:106:67:118:59:130$1:0:0:13:130:103:130$1:12:13:30:145:30:173$1:2:2:30:145:85:145$1:22:23:85:145:85:173$1:2:2:30:173:85:173","u660e-08":"99:0:0:48:-1:164:173:u65e5-01$99:0:0:54:0:148:200:u6708-02","u65e5-01":"99:0:0:10:11:87:177:u65e5","u65e5":"1:12:13:46:32:46:168$1:2:2:46:32:154:32$1:22:23:154:32:154:168$1:2:2:46:98:154:98$1:2:2:46:168:154:168","u6708-02":"7:12:7:115:29:115:104:115:172:64:188$1:2:2:115:29:172:29$1:22:4:172:29:172:182$1:2:2:114:74:172:74$1:2:2:114:119:172:119","u2a8e6":"99:0:0:3:5:160:195:u571f-01$99:0:0:61:0:199:200:u660e","u571f-01":"1:0:0:15:70:87:70$1:0:32:50:18:50:141$2:0:7:15:157:44:148:88:129","u660e":"99:0:0:-2:-1:234:177:u65e5-01$99:0:0:-3:0:197:200:u6708-02","u2a93e":"99:0:0:0:0:200:200:u2a93e-jv","u2a93e-jv":"99:0:0:0:9:200:84:u5915$99:0:0:0:71:200:194:u671d-ue0101","u5915":"2:0:7:96:17:76:73:24:113$1:2:2:84:45:165:45$2:22:7:165:45:134:155:24:187$2:7:8:65:74:100:94:113:119","u671d-ue0101":"99:0:0:-5:0:238:200:u9fba:0:0:0$99:0:0:34:0:197:200:u6708-02-var-005:0:0:0","u9fba":"1:0:0:18:38:97:38$1:0:32:57:14:57:65$1:12:13:31:65:31:115$1:2:2:31:65:84:65$1:22:23:84:65:84:115$1:2:2:31:90:84:90$1:2:2:31:115:84:115$1:0:0:15:148:100:148$1:32:0:57:115:57:186","u6708-02-var-005":"7:12:7:115:29:115:104:115:172:64:188$1:2:2:115:29:172:29$1:22:4:172:29:172:182$2:7:8:123:61:145:71:157:88$2:7:8:123:106:145:116:157:133","u2ab42":"99:0:0:1:3:190:144:u7ae0-01$99:0:0:89:5:195:142:u6709$99:0:0:0:33:200:198:u5fc3-04","u7ae0-01":"1:0:32:61:14:61:38$1:0:0:19:38:103:38$2:7:8:36:43:44:52:48:70$2:0:7:82:43:76:57:68:74$1:0:0:13:74:108:74$1:12:13:32:91:32:130$1:2:2:32:91:88:91$1:22:23:88:91:88:130$1:2:2:32:130:88:130$1:2:2:32:110:88:110$1:0:0:12:156:110:156$1:32:0:61:130:61:186","u6709":"2:0:7:91:14:67:93:15:133$1:0:0:14:48:186:48$1:12:0:67:80:67:186$1:2:2:67:80:150:80$1:22:4:150:80:150:182$1:2:2:67:111:150:111$1:2:2:67:142:150:142","u5fc3-04":"99:0:0:0:54:200:254:u5fc3-09","u5fc3-09":"2:7:8:37:70:38:105:18:118$3:0:5:66:71:66:122:147:122$2:7:8:87:65:107:75:118:95$2:7:8:148:72:172:88:179:113","u2ad1e":"99:0:0:7:0:107:200:u697d$99:0:0:94:0:193:200:u660e","u697d":"99:0:0:0:0:200:200:u2ffb-cdp-89ae-u767d@1
:0:0:0$99:0:0:0:31:200:198:u6728-04:0:0:0","u2ffb-cdp-89ae-u767d":"99:0:0:0:13:200:125:cdp-89ae-05:0:0:0$99:0:0:55:6:145:117:u767d-07-var-002:0:0:0","cdp-89ae-05":"2:7:8:21:28:39:50:50:85$2:0:7:18:171:43:142:67:113$2:0:7:175:37:161:64:138:96$2:7:8:137:115:162:132:180:164","u767d-07-var-002":"2:0:7:104:15:96:29:72:62$99:0:0:-8:37:208:194:u65e5:0:0:0","u6728-04":"1:0:0:18:114:182:114$1:0:0:100:85:100:186$2:32:7:94:114:67:158:13:180$2:7:0:105:114:135:152:180:172","u2aeea":"99:0:0:0:-1:205:200:u738b-01$0:0:0:0$99:0:0:69:0:193:200:u660e","u738b-01":"1:0:0:14:42:75:42$1:32:32:41:42:41:149$1:0:0:17:93:72:93$2:0:7:14:160:43:150:78:135","u2b039":"99:0:0:1:0:180:200:u79be-01$0:0:0:0$99:0:0:73:0:193:200:u660e","u79be-01":"2:0:7:82:23:62:34:15:45$1:0:0:13:76:90:76$1:32:0:53:35:53:186$2:32:7:50:76:40:125:13:159$2:7:8:55:98:74:106:85:121","u2b101":"99:0:0:3:0:136:200:u7cf8-01$99:0:0:65:0:192:200:u840c@8
","u7cf8-01":"2:0:7:66:16:52:37:35:56$2:7:8:14:45:38:56:48:76$2:0:7:95:39:67:76:34:110$2:0:7:16:113:58:109:95:101$2:7:8:74:78:93:91:101:114$1:32:0:62:109:62:186$2:0:7:38:127:34:155:14:180$2:7:8:75:122:93:136:100:161","u840c":"99:0:0:0:2:200:175:u8279-03$99:0:0:0:47:200:195:u660e","u8279-03":"1:0:0:13:39:187:39$1:0:0:72:13:72:64$1:0:0:128:13:128:64","u2b471":"99:0:0:0:0:200:200:u2b471-jv","u2b471-jv":"99:0:0:8:0:100:200:aj1-08635$99:0:0:90:0:192:200:u671d-ue0101","aj1-08635":"99:0:0:0:0:220:200:u826f-01$99:0:0:0:0:200:200:u961d-02","u826f-"

2015-07-20 15:05 GMT+08:00 caasi Huang notifications@github.com:

**Comment by yapcheahshen** [comment]
Fetch API cannot load http://chikage.linode.caasih.net/exploded/?inputs=%F0%AA%B5%B8%F0%AB%A7%9C%F0%AB%AD%A9%F0%AC%B5%8D. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://rawgit.com' is therefore not allowed access. The response had HTTP status code 502.

**Comment by caasi** [comment]
日月那個問題，今天晚上會看看那邊有錯。

`Access-Control-Allow-Origin:*`

CORS 確定有開，一開始就有開。

**Comment by yapcheahshen** [comment]
輸入「日月」，勾深拆
回應的json 不對，似乎都會被 truncate
Uncaught (in promise) SyntaxError: Unexpected end of input

2015-07-22 12:32 GMT+08:00 caasi Huang notifications@github.com:

**Comment by caasi** [comment]
會不會是因為 reader 是個 [stream](https://github.com/yutakahirano/fetch-with-streams/blob/master/README.md#fetch-api) 的關係？

**Comment by yapcheahshen** [comment]
真是一語警醒夢中人！的確是reader 的問題。
但還是有一些部件出不來。

2015-07-23 0:59 GMT+08:00 caasi Huang notifications@github.com:

**Comment by caasi** [comment]
有鎖定是哪幾個字嗎？

加了一個 API 是查看抓了樹但是還沒壓扁成物件的：

`http://chikage.linode.caasih.net/forest/?inputs=%F0%AA%A2%A3%F0%AA%A3%A6%F0%AA%A4%BE`

**Comment by yapcheahshen** [comment]
我發現問題所在：
chikage 返回: (多了 @8 )
"u2b101": "99:0:0:3:0:136:200:u7cf8-01$99:0:0:65:0:192:200:u840c@8"

必須是這樣才可以：
, "u2b101": "99:0:0:3:0:136:200:u7cf8-01$99:0:0:65:0:192:200:u840c"

所以我直接把@n去掉即可。

2015-07-23 12:15 GMT+08:00 caasi Huang notifications@github.com:

**Comment by caasi** [comment]
尷尬，新的資料都多了 `@` ，例如：

`aj1-00517\@1                                                              | u3013   | 99:0:0:0:0:200:200:u3041-halfwidth@1`

我先開另外一個 issue ，之後改寫處理 `dump.tar.gz` 那段時再查 `@` 代表什麼意義、該參考什麼文件。

**Comment by yapcheahshen** [comment]
kage 目前還不吃 @\d+
我先replace 掉，目前還沒發現任何問題

caasi Huang notifications@github.com 於 2015年7月23日 下午2:24 寫道：

**Comment by caasi** [comment]
那先關掉這個 issue ，缺資料就到 #3 或者另外再開。
