### ISSUE TITLE
u2b78e 返回資料缺少

### ISSUE THREAD

**Issue by yapcheahshen** [g0v/chikage#3]
http://chikage.linode.caasih.net/exploded/?inputs=%F0%AB%9E%8E
{"u2b78e":"99:0:0:2:0:172:200:u6728-01:0:0:0$99:0:0:67:0:198:200:u2ff1-u2ff8-u20087-cdp-865e-u518b:0:0:0"
,"u6728-01":"1:0:0:13:61:90:61$1:0:0:53:15:53:186$2:32:7:50:61:40:110:13:148$2:7:8:55:86:74:94:85:109"
,"u2ff1-u2ff8-u20087-cdp-865e-u518b":"1:0:0:15:33:185:33$2:0:7:84:15:57:62:13:85$99:200:5:0:28:200:198:u2ff1-cdp-865e-u518b:0:0:10"}

漏了 u2ff1-cdp-865e-u518b

**Comment by yapcheahshen** [comment]
大部份都ok了，除了
U+2B78E http://www.unicode.org/cgi-bin/GetUnihanData.pl?codepoint=2B78E
 (輸入「木口」)

2015-07-25 21:31 GMT+08:00 caasi Huang notifications@github.com:

**Comment by caasi** [comment]
剛剛那個 commit 就是為了它。[看來是有好好拆到末級部件](http://chikage.linode.caasih.net/forest/?inputs=%F0%AB%9E%8E)了，但 server 比 commit 慢了幾分鐘更新。

**Comment by yapcheahshen** [comment]
ok,
cdn.rawgit.com 的確需要一些時間和commit 同步
yap

2015-07-25 21:43 GMT+08:00 caasi Huang notifications@github.com:

**Comment by caasi** [comment]
500 了，我看看那邊出問題 XD

**Comment by caasi** [comment]
解決了，我沒寫好 RegExp 。

**Comment by yapcheahshen** [comment]
GREAT !!!!

2015-07-25 22:00 GMT+08:00 caasi Huang notifications@github.com:
